pipeline {
    agent any
    environment{
	image_tag = "amitp30/nodeapp:$BUILD_NUMBER"
    }
    stages {
        stage('Build image') {
            steps {
                echo 'Building docker image...!!'
                sh 'docker build -t $image_tag .'
            }
        }
        stage('Push image'){
        	steps{
        		script{
        			withDockerRegistry(credentialsId: 'docker-hub-amitp30', url: '') {
        				sh 'docker push $image_tag'
        			}
        		}
        	}
        }
    }
}
